version: '3.9'

services:
  database:
    image: postgres
    container_name: mezaptenant
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=webck@dev
      - POSTGRES_DB=mezaptenant
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local